In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [47]:
df = pd.read_csv('cleaned_evictions.csv').drop(columns=['Unnamed: 0', 'ID', 'Supervisor District', 'Neighborhood', 'Zipcode', 'Address'])
df.head()

,File Date,Non Payment,Breach,Nuisance,Illegal Use,Failure to Sign Renewal,Access Denial,Unapproved Subtenant,Owner Move In,Demolition,...,Substantial Rehab,Ellis Act WithDrawal,Condo Conversion,Roommate Same Unit,Other Cause,Late Payments,Lead Remediation,Development,Good Samaritan Ends,Shape
0,2002-10-09,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,POINT (-122.44458 37.791653)
1,2020-11-12,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,2007-02-08,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,POINT (-122.42439 37.76721)
3,2020-05-05,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
4,2020-03-06,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN

In [48]:
len(df) - len(df.dropna())

60

In [49]:
df = df.dropna()

In [50]:
df['Shape'] = df.Shape.str.slice(start=5)
df[['lon','lat']] = pd.DataFrame(df.Shape.str.strip(' ').str.split(' ').tolist(), index= df.index)
df.drop(columns='Shape', inplace=True)
df['lon'] = df.lon.str.slice(start=1)
df['lat'] = df.lat.str.slice(stop=-1)

df.head()

,File Date,Non Payment,Breach,Nuisance,Illegal Use,Failure to Sign Renewal,Access Denial,Unapproved Subtenant,Owner Move In,Demolition,...,Ellis Act WithDrawal,Condo Conversion,Roommate Same Unit,Other Cause,Late Payments,Lead Remediation,Development,Good Samaritan Ends,lon,lat
0,2002-10-09,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,-122.44458,37.791653
2,2007-02-08,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,-122.42439,37.76721
5,2019-11-26,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-122.418526,37.788204
6,2019-09-09,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,-122.4375,37.77982
7,2019-08-21,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-122.41251,37.800182

In [53]:
df.columns

Index(['File Date', 'Non Payment', 'Breach', 'Nuisance', 'Illegal Use',
       'Failure to Sign Renewal', 'Access Denial', 'Unapproved Subtenant',
       'Owner Move In', 'Demolition', 'Capital Improvement',
       'Substantial Rehab', 'Ellis Act WithDrawal', 'Condo Conversion',
       'Roommate Same Unit', 'Other Cause', 'Late Payments',
       'Lead Remediation', 'Development', 'Good Samaritan Ends', 'lon', 'lat'],
      dtype='object')

#### Next step is to convert and store all tracts

- Dataset: df
- Goal: Use [FCC Census API](https://geo.fcc.gov/api/census/#!/block/get_block_find) to convert all locations of evictions into their corresponding census block

In [55]:
import requests

In [57]:
def get_block(lat, lon):
    coords = {'lat': lat, 'lon': lon}
    r = requests.get('https://geo.fcc.gov/api/census/block/find', params=coords)
    return r.json()['results'][0]['block_fips']#[:11]

In [63]:
get_block(37.791653, -122.44458)

'060750132003015'

In [64]:
len(df)

42182

In [66]:
df['block'] = df[['lat', 'lon']].apply(lambda x: get_block(x.lat, x.lon), axis=1)
df.head()

,File Date,Non Payment,Breach,Nuisance,Illegal Use,Failure to Sign Renewal,Access Denial,Unapproved Subtenant,Owner Move In,Demolition,...,Condo Conversion,Roommate Same Unit,Other Cause,Late Payments,Lead Remediation,Development,Good Samaritan Ends,lon,lat,block
0,2002-10-09,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,-122.44458,37.791653,060750132003015
2,2007-02-08,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,-122.42439,37.76721,060750202002003
5,2019-11-26,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,-122.418526,37.788204,060750120001006
6,2019-09-09,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,-122.4375,37.77982,060750158012019
7,2019-08-21,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,-122.41251,37.800182,060750103002005

In [67]:
df.to_csv('temp_evictions_w_block.csv')

In [24]:
# df['Total Evictions'] = 1

# grouped = df.groupby('Address').agg({
#     'Zipcode': 'first',
#     'Neighborhood': 'first',
#     'Shape': 'first',
#     'File Date': list,
#     'Non Payment' : sum, 
#     'Breach' : sum, 
#     'Nuisance' : sum,
#     'Illegal Use' : sum, 
#     'Failure to Sign Renewal' : sum, 
#     'Access Denial' : sum,
#     'Unapproved Subtenant' : sum,
#     'Owner Move In' : sum,
#     'Demolition' : sum,
#     'Capital Improvement' : sum, 
#     'Substantial Rehab' : sum, 
#     'Ellis Act WithDrawal' : sum,
#     'Condo Conversion' : sum, 
#     'Roommate Same Unit' : sum,
#     'Other Cause' : sum,
#     'Late Payments' : sum, 
#     'Lead Remediation' : sum,
#     'Development' : sum,
#     'Good Samaritan Ends' : sum,
#     'Total Evictions': sum
# })
# grouped.head()

,Zipcode,Neighborhood,Shape,File Date,Non Payment,Breach,Nuisance,Illegal Use,Failure to Sign Renewal,Access Denial,...,Substantial Rehab,Ellis Act WithDrawal,Condo Conversion,Roommate Same Unit,Other Cause,Late Payments,Lead Remediation,Development,Good Samaritan Ends,Total Evictions
Address,,,,,,,,,,,,,,,,,,,,,
0 Block Of 01/2 2 Mirabel,94110.0,Bernal Heights,POINT (-122.41649 37.746468),[1997-06-30],0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
0 Block Of 05th Avenue,94118.0,Inner Richmond,POINT (-122.46369 37.787704),"[2017-10-10, 2013-07-30, 1997-10-09]",0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,3
0 Block Of 06th Avenue,94118.0,Inner Richmond,POINT (-122.46475 37.787525),"[2009-01-27, 1999-05-19, 1997-09-30, 1997-08-2...",0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
0 Block Of 06th Street,94103.0,South of Market,POINT (-122.40947 37.781578),"[2010-05-07, 2020-11-10, 2019-07-12, 2020-12-2...",3,6,88,0,0,0,...,0,0,0,0,0,0,0,0,0,96
0 Block Of 07th Avenue,94118.0,Inner Richmond,POINT (-122.46582 37.78744),"[2007-05-08, 2007-05-08, 2007-05-08, 2007-05-0...",0,0,0,0,0,0,...,0,5,0,0,0,0,0,0,0,5